services:
  - type: web
    name: tripease-api
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /api/health

    envVars:
      - key: DB_URL
        fromDatabase:
          name: tripease-db
          property: connectionString

      - key: DB_USERNAME
        fromDatabase:
          name: tripease-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: tripease-db
          property: password

      - key: JWT_SECRET
        generateValue: true

      - key: CORS_ORIGINS
        sync: false

      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: tripease-db
    plan: free