package com.tripease.service;

import com.tripease.dto.Dtos.PricePoint;
import com.tripease.dto.Dtos.PriceSeries;
import com.tripease.model.Hotel;
import com.tripease.model.Trip;
import com.tripease.util.AppClock;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Random;

/**
 * Demand-based dynamic pricing engine.
 *
 * There is no real airline/railway supplier behind this demo, so prices are generated by a
 * deterministic model: base fare x (days-to-departure demand) x (weekday) x (small stable noise).
 * The same function feeds search results, price graphs, AI insights and the final booking amount,
 * so every screen always agrees. Swap this class for a real supplier API to go live.
 */
@Service
public class PricingService {

    // ------------------------------------------------------------ trips

    public BigDecimal tripPrice(Trip trip, LocalDate travelDate) {
        return tripPrice(trip, travelDate, AppClock.today());
    }

    /** Price of a trip for {@code travelDate} if it were booked on {@code bookingDate}. */
    public BigDecimal tripPrice(Trip trip, LocalDate travelDate, LocalDate bookingDate) {
        long daysAhead = Math.max(0, ChronoUnit.DAYS.between(bookingDate, travelDate));
        double sensitivity = switch (trip.getMode()) {
            case FLIGHT -> 1.0;
            case BUS -> 0.6;
            case TRAIN -> 0.35;
        };
        double factor = 1 + (demandFactor(daysAhead) * weekdayFactor(travelDate.getDayOfWeek()) - 1) * sensitivity;
        double price = trip.getBasePrice().doubleValue() * factor * (1 + noise(trip.getId(), travelDate, 0.06));
        return roundTo5(price);
    }

    /** Seats already sold by "other customers" - keeps the demo realistic. */
    public int baselineSold(Trip trip, LocalDate date) {
        int total = trip.getTotalSeats();
        int min = (int) (total * 0.15);
        int spread = Math.max(1, (int) (total * 0.60));
        return min + new Random(trip.getId() * 7919L + date.toEpochDay()).nextInt(spread);
    }

    public PriceSeries tripSeries(Trip trip, LocalDate selected, int days) {
        LocalDate today = AppClock.today();
        LocalDate sel = selected.isBefore(today) ? today : selected;
        LocalDate start = sel.minusDays(10).isBefore(today) ? today : sel.minusDays(10);
        List<PricePoint> points = new ArrayList<>();
        for (int i = 0; i < days; i++) {
            LocalDate d = start.plusDays(i);
            points.add(new PricePoint(d, tripPrice(trip, d)));
        }
        return summarise(trip.getOperator() + " " + trip.getCode(), points, sel, tripPrice(trip, sel));
    }

    // ------------------------------------------------------------ hotels

    public BigDecimal hotelNightPrice(Hotel hotel, LocalDate night) {
        return hotelNightPrice(hotel, night, AppClock.today());
    }

    public BigDecimal hotelNightPrice(Hotel hotel, LocalDate night, LocalDate bookingDate) {
        long daysAhead = Math.max(0, ChronoUnit.DAYS.between(bookingDate, night));
        DayOfWeek dow = night.getDayOfWeek();
        double weekend = (dow == DayOfWeek.FRIDAY || dow == DayOfWeek.SATURDAY) ? 1.18 : 1.0;
        double season = switch (night.getMonthValue()) {
            case 10, 11, 12, 1 -> 1.20;   // festive / winter peak
            case 4, 5 -> 0.90;            // summer lull
            default -> 1.0;
        };
        double demand = 1 + (demandFactor(daysAhead) - 1) * 0.35;
        double price = hotel.getBasePrice().doubleValue() * weekend * season * demand
                * (1 + noise(hotel.getId() + 10_000L, night, 0.08));
        return roundTo5(price);
    }

    /** Total for ONE room for the whole stay. */
    public BigDecimal hotelStayTotal(Hotel hotel, LocalDate checkIn, LocalDate checkOut) {
        BigDecimal total = BigDecimal.ZERO;
        for (LocalDate d = checkIn; d.isBefore(checkOut); d = d.plusDays(1)) {
            total = total.add(hotelNightPrice(hotel, d));
        }
        return total;
    }

    public int baselineOccupied(Hotel hotel, LocalDate date) {
        int total = hotel.getRoomsTotal();
        int min = (int) (total * 0.20);
        int spread = Math.max(1, (int) (total * 0.50));
        return min + new Random(hotel.getId() * 6271L + date.toEpochDay()).nextInt(spread);
    }

    public PriceSeries hotelSeries(Hotel hotel, LocalDate selected, int days) {
        LocalDate today = AppClock.today();
        LocalDate sel = selected.isBefore(today) ? today : selected;
        LocalDate start = sel.minusDays(10).isBefore(today) ? today : sel.minusDays(10);
        List<PricePoint> points = new ArrayList<>();
        for (int i = 0; i < days; i++) {
            LocalDate d = start.plusDays(i);
            points.add(new PricePoint(d, hotelNightPrice(hotel, d)));
        }
        return summarise(hotel.getName() + " (per night)", points, sel, hotelNightPrice(hotel, sel));
    }

    // ------------------------------------------------------------ helpers

    /** Fares climb as departure approaches and are cheapest when booked far ahead. */
    static double demandFactor(long daysAhead) {
        if (daysAhead <= 1) return 1.45;
        if (daysAhead <= 3) return 1.32;
        if (daysAhead <= 7) return 1.20;
        if (daysAhead <= 14) return 1.08;
        if (daysAhead <= 30) return 1.00;
        if (daysAhead <= 60) return 0.94;
        return 0.90;
    }

    static double weekdayFactor(DayOfWeek dow) {
        return switch (dow) {
            case FRIDAY -> 1.08;
            case SATURDAY -> 1.06;
            case SUNDAY -> 1.12;
            default -> 1.0;
        };
    }

    /** Stable pseudo-random value in [-amplitude, +amplitude] for the same (id, date). */
    private static double noise(Long id, LocalDate date, double amplitude) {
        Random r = new Random(id * 1_000_003L + date.toEpochDay());
        return (r.nextDouble() * 2 - 1) * amplitude;
    }

    private static BigDecimal roundTo5(double value) {
        return BigDecimal.valueOf(Math.round(value / 5.0) * 5L);
    }

    private PriceSeries summarise(String label, List<PricePoint> points, LocalDate selected, BigDecimal selectedPrice) {
        PricePoint cheapest = points.stream().min(Comparator.comparing(PricePoint::price)).orElseThrow();
        BigDecimal max = points.stream().map(PricePoint::price).max(Comparator.naturalOrder()).orElse(BigDecimal.ZERO);
        double avg = points.stream().mapToDouble(p -> p.price().doubleValue()).average().orElse(0);
        double pct = avg == 0 ? 0 : (selectedPrice.doubleValue() - avg) / avg * 100;
        return new PriceSeries(label, points, selected, selectedPrice, cheapest.price(), max,
                BigDecimal.valueOf(Math.round(avg)), cheapest.date(), Math.round(pct * 10) / 10.0);
    }
}
